drop table if exists CANDIDATE_DATA;

create table CANDIDATE_DATA (
	id INTEGER PRIMARY KEY,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	country VARCHAR(50),
	gender VARCHAR(50),
	skill VARCHAR(50),
	years_experience INTEGER
);

insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (3965, 'Debora', 'Fishleigh', 'Honduras', 'Female', 'Guest Lecturing', 25);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (8663, 'Mirelle', 'Pitkins', 'Serbia', 'Female', 'BTEQ', 7);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (9622, 'Shani', 'Knowlys', 'Philippines', 'Female', 'Natural Language Processing', 18);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (1527, 'Sula', 'Hayller', 'Brazil', 'Female', 'Natural Language Processing', 9);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (1695, 'Claresta', 'Danilovic', 'Mexico', 'Female', 'XPlanner', 11);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (3210, 'Felicio', 'Matei', 'China', 'Male', 'SAP MDM', 9);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (6997, 'Valerye', 'Mundie', 'China', 'Female', 'PET-CT', 9);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (4022, 'Wake', 'Stearn', 'Thailand', 'Male', 'Natural Language Processing', 20);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (7687, 'Timoteo', 'Perview', 'Indonesia', 'Male', 'DLNA', 18);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (7446, 'Salaidh', 'Spoerl', 'Russia', 'Female', 'Organization Skills', 5);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (9917, 'Lorant', 'Bentzen', 'Japan', 'Male', 'Yellow Belt', 25);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (8530, 'Marve', 'Kensitt', 'France', 'Male', 'Company Set-up', 10);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (9573, 'Baudoin', 'Milmo', 'Indonesia', 'Male', 'Online Reputation Management', 2);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (4543, 'Rosmunda', 'Ocheltree', 'Sweden', 'Female', 'TSW', 19);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (2057, 'Fonsie', 'McPike', 'Mongolia', 'Male', 'Crisis Communications', 3);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (8600, 'Kris', 'Spire', 'Thailand', 'Male', 'Army', 14);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (6557, 'Tallou', 'Wimpey', 'Ukraine', 'Female', 'Kondor+', 6);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (8447, 'Alethea', 'Gras', 'New Caledonia', 'Agender', 'ISO 14001', 8);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (2166, 'Farrell', 'Foskett', 'China', 'Male', 'Black &amp; White Photography', 23);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (3160, 'Jaimie', 'Magee', 'Indonesia', 'Male', 'FDS', 25);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (9326, 'Dolf', 'Duerden', 'Japan', 'Male', 'Vray', 25);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (3676, 'Halie', 'Pavelka', 'Japan', 'Female', 'HMI Configuration', 4);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (3665, 'Carma', 'Murty', 'Thailand', 'Female', 'Screening Resumes', 17);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (1586, 'Noelle', 'Goligher', 'France', 'Female', 'MPEG Streamclip', 21);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (9062, 'Bradan', 'Bretherick', 'Indonesia', 'Male', 'High Rise', 21);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (4214, 'Zach', 'Greenall', 'United States', 'Male', 'Farms', 19);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (8402, 'Leesa', 'Amdohr', 'China', 'Female', 'Xilinx', 11);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (9896, 'Lorilyn', 'Cotes', 'Colombia', 'Female', 'Gx', 3);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (4450, 'Jania', 'Norville', 'Poland', 'Female', 'Facebook', 24);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (6000, 'Charisse', 'Rodriguez', 'China', 'Female', 'HSM', 25);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (4006, 'Marchelle', 'Vango', 'Brazil', 'Female', 'VPython', 20);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (3237, 'Frants', 'Gilstoun', 'Indonesia', 'Male', 'RCS Selector', 2);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (3631, 'Cassie', 'Tireman', 'China', 'Male', 'MS-DOS', 7);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (5402, 'Fairlie', 'Gurney', 'Honduras', 'Male', 'Onboarding', 1);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (5980, 'Haskel', 'Gabotti', 'Colombia', 'Male', 'HVAC', 2);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (2317, 'Bond', 'Edelman', 'Mexico', 'Male', 'JBPM', 12);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (7982, 'Nessy', 'Bartomeu', 'Hungary', 'Female', 'PV', 8);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (3639, 'Bella', 'McClure', 'Colombia', 'Female', 'Active-HDL', 23);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (2162, 'Gerardo', 'Bellelli', 'Germany', 'Male', 'Key Performance Indicators', 6);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (7673, 'Xylina', 'Normanville', 'South Africa', 'Female', 'XBR', 7);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (4762, 'Lindsay', 'Frudd', 'Ireland', 'Female', 'Pre-owned', 9);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (5375, 'Cass', 'Jolliman', 'Morocco', 'Male', 'TCF', 11);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (3447, 'Gilli', 'Collington', 'Indonesia', 'Female', 'Koi Ponds', 15);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (6827, 'Staffard', 'Goode', 'Colombia', 'Male', 'OOH', 5);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (6762, 'Hughie', 'Pittoli', 'Russia', 'Male', 'CTIOS', 22);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (8404, 'Clerc', 'Hollyar', 'Laos', 'Male', 'NIST', 2);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (4510, 'Caleb', 'Klammt', 'Portugal', 'Male', 'Eggs', 6);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (3754, 'Germayne', 'D''Arrigo', 'Kazakhstan', 'Male', 'Ethnography', 6);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (9130, 'Linnea', 'Barrus', 'China', 'Female', 'Aerobics', 6);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (7158, 'Leon', 'Millimoe', 'Philippines', 'Male', 'Red Hat Linux', 24);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (4197, 'Virgil', 'Dundridge', 'China', 'Male', 'Nutrition', 17);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (1106, 'Johan', 'Tyne', 'Russia', 'Male', 'HVDC', 5);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (2983, 'Alikee', 'Clabburn', 'China', 'Female', 'Long-term Customer Relationships', 1);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (6392, 'Joya', 'Mc Grath', 'Indonesia', 'Female', 'Psychopharmacology', 22);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (2476, 'Elsi', 'Woolliams', 'North Korea', 'Female', 'Data Mining', 8);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (2033, 'Bidget', 'Knath', 'China', 'Genderqueer', 'EKG', 5);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (4004, 'Stepha', 'Rubinowitch', 'Russia', 'Non-binary', 'Data Center', 3);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (6697, 'Sheffy', 'Pittam', 'United States', 'Male', 'DDR3', 1);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (7320, 'Hansiain', 'Hussell', 'Portugal', 'Male', 'Waterfall', 3);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (5046, 'Genevieve', 'Russel', 'Poland', 'Female', 'Health Economics', 5);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (9396, 'Say', 'Burnand', 'Russia', 'Male', 'CSPro', 6);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (9755, 'Zora', 'Barkes', 'Philippines', 'Female', 'Knowledge Discovery', 2);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (2519, 'Aleda', 'Tulloch', 'China', 'Female', 'RMX', 22);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (3905, 'Fayette', 'Panks', 'Egypt', 'Female', 'Ffmpeg', 12);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (7884, 'Marcos', 'Devanney', 'China', 'Male', 'Copy Typing', 16);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (7903, 'Caroline', 'Bonnette', 'Japan', 'Polygender', 'IGBT', 15);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (1251, 'Benny', 'Baybutt', 'Malta', 'Male', 'FCNSA', 19);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (1702, 'Merci', 'Henfre', 'China', 'Female', 'RAN', 14);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (7580, 'Salli', 'Egerton', 'Uruguay', 'Female', 'PVTsim', 7);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (6900, 'Ermengarde', 'Morgans', 'China', 'Female', 'HTRI Software', 1);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (1097, 'Faun', 'Meadowcraft', 'China', 'Non-binary', 'Cardiac Rhythm Management', 2);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (6732, 'Demetris', 'Hunnawill', 'France', 'Genderfluid', 'American Sign Language', 14);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (9087, 'Gusta', 'Tildesley', 'Poland', 'Female', 'XSL', 2);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (1567, 'Roselia', 'Nunan', 'Thailand', 'Female', 'MPIO', 2);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (4985, 'Corney', 'Pallin', 'Nepal', 'Male', 'Small Business Online Marketing', 11);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (6141, 'Katleen', 'Epelett', 'France', 'Female', 'Xytech', 1);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (6266, 'Nappy', 'Burstowe', 'Poland', 'Male', 'Mac OS', 2);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (6397, 'Olympia', 'Winterton', 'Indonesia', 'Female', 'Software Testing Life Cycle', 18);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (1868, 'Leora', 'Kunkel', 'Russia', 'Female', 'Small Business', 18);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (9941, 'Carilyn', 'Kop', 'Japan', 'Female', 'LSI', 18);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (3352, 'Marysa', 'Quail', 'China', 'Female', 'Adobe Creative Suite', 5);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (5650, 'Elias', 'Ilyinykh', 'Philippines', 'Male', 'Gym', 15);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (7890, 'Pauly', 'Kubacki', 'China', 'Female', 'Feature Articles', 22);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (7869, 'Bobbye', 'Freda', 'Indonesia', 'Female', 'ProSystem fx Tax', 2);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (1881, 'Hephzibah', 'Dooly', 'Hungary', 'Female', 'Object Pascal', 4);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (4782, 'Alex', 'Bernier', 'Indonesia', 'Male', 'Career Counseling', 13);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (1292, 'Rip', 'Thorneywork', 'Indonesia', 'Male', 'MCAD', 14);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (3278, 'Maryanne', 'Dobel', 'Sweden', 'Agender', 'Flex', 24);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (6709, 'Gerome', 'Platfoot', 'Czech Republic', 'Male', 'WMI', 1);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (1891, 'Hestia', 'Blaxley', 'Portugal', 'Genderfluid', 'FCC License', 19);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (2443, 'Ronna', 'Siney', 'Thailand', 'Female', 'RNAseq', 18);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (9399, 'Allistir', 'Tettersell', 'France', 'Male', 'QIP', 21);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (9932, 'Corbie', 'Gornar', 'Sweden', 'Male', 'z/OS', 15);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (2182, 'Marget', 'Brightling', 'China', 'Female', 'CDM Co-ordinator', 17);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (6366, 'Abagail', 'Bortol', 'China', 'Female', 'PMO', 24);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (2994, 'Vickie', 'Perrygo', 'Lithuania', 'Female', 'VPM', 24);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (5171, 'Antoinette', 'Speariett', 'Chad', 'Female', 'Online Travel', 9);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (9693, 'Harmonie', 'Threader', 'Brazil', 'Polygender', 'Fashion Photography', 9);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (5605, 'Sharlene', 'Duell', 'China', 'Female', 'CM Synergy', 9);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (6260, 'Connie', 'Sidnell', 'Russia', 'Male', 'GMLAN', 2);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (7096, 'Dianne', 'Ludgate', 'Netherlands', 'Female', 'Portraits', 24);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (7624, 'Jody', 'Shoreman', 'New Caledonia', 'Female', 'iFix', 5);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (8253, 'Ogdan', 'Drance', 'Ukraine', 'Non-binary', 'Ukulele', 18);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (2731, 'Lynnette', 'Heningham', 'Brazil', 'Female', 'LSP', 2);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (3462, 'Zane', 'Gercken', 'South Korea', 'Male', 'Local Government', 12);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (3859, 'Misha', 'Rebichon', 'Indonesia', 'Genderqueer', 'Technical Support', 3);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (7453, 'Glori', 'Waples', 'Russia', 'Female', 'HDV', 16);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (6444, 'Arny', 'Schoolfield', 'China', 'Male', 'FSMS', 16);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (9876, 'Andras', 'Garz', 'Vietnam', 'Male', 'HR Solutions', 23);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (6967, 'Lorens', 'Marjanovic', 'Kenya', 'Male', 'CMiC', 19);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (8828, 'Jemmie', 'Cars', 'Albania', 'Female', 'Computer Science', 13);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (2279, 'Freeman', 'Seiler', 'Brazil', 'Male', 'Government Relations', 17);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (3726, 'Paxton', 'Markovic', 'China', 'Male', 'Amadeus GDS', 22);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (5890, 'Klarika', 'Van Arsdall', 'Ukraine', 'Female', 'IBM Certified', 6);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (2607, 'Florette', 'Pointer', 'Afghanistan', 'Female', 'RCDD', 16);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (2918, 'Tannie', 'Densham', 'China', 'Male', 'Access Control', 18);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (6233, 'Alyssa', 'Alltimes', 'Poland', 'Female', 'Warehousing', 18);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (9180, 'Sonny', 'Jopke', 'France', 'Agender', 'Upholstery', 3);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (2005, 'Dorothee', 'Cranidge', 'Tanzania', 'Female', 'Power Electronics', 19);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (4478, 'Tedman', 'Snasdell', 'Sri Lanka', 'Male', 'Google Earth', 2);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (2151, 'Clementia', 'McKelvie', 'Luxembourg', 'Female', 'GNU Octave', 2);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (2491, 'Frederique', 'Gathercole', 'Tajikistan', 'Female', 'NDA', 25);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (2399, 'Beverley', 'Glazebrook', 'Palestinian Territory', 'Female', '7 QC Tools', 8);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (2034, 'Bendick', 'Bauckham', 'Philippines', 'Male', 'Chromatography', 18);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (8386, 'Mae', 'Doumic', 'Poland', 'Female', 'Tax Accounting', 10);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (7040, 'Greg', 'Fairweather', 'Kenya', 'Male', 'TDA', 14);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (6475, 'Gerrard', 'McCullogh', 'China', 'Male', 'EWB', 22);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (6641, 'Peirce', 'Padilla', 'China', 'Male', 'DME', 5);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (9897, 'Pietro', 'Gross', 'Indonesia', 'Male', 'HIPAA', 25);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (9313, 'Camile', 'Cradock', 'China', 'Female', 'Managerial Finance', 16);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (6308, 'Cornie', 'Bousler', 'Indonesia', 'Male', 'European Union Politics', 20);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (6544, 'Mathe', 'Scally', 'Serbia', 'Male', 'Gardening', 7);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (4866, 'Chancey', 'Cowope', 'Kazakhstan', 'Male', 'IAS 39', 16);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (7839, 'Bree', 'Deighan', 'Netherlands', 'Female', 'Pneumatic Tools', 8);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (8082, 'Licha', 'Vescovini', 'France', 'Female', 'Financial Risk Management', 22);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (1725, 'Anneliese', 'Nodes', 'China', 'Agender', 'Hg', 14);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (1674, 'Falito', 'Barnsdall', 'China', 'Male', 'Jet Fuel', 21);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (6996, 'Doro', 'Izkovici', 'Indonesia', 'Female', 'Jive SBS', 22);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (5797, 'Ethelred', 'Barnby', 'Ukraine', 'Male', 'UK Tax', 4);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (3979, 'Laurena', 'Fairfoul', 'Ukraine', 'Female', 'Affirmative Action', 16);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (9437, 'Ciel', 'Brayshaw', 'Greece', 'Female', 'Ocean', 19);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (2027, 'Leshia', 'Phizacklea', 'Palestinian Territory', 'Female', 'Italian', 23);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (1941, 'Madelle', 'Domleo', 'Samoa', 'Female', 'CMiC', 4);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (4165, 'Alida', 'Krale', 'Argentina', 'Female', 'JBL', 4);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (7237, 'Trudey', 'Baggot', 'China', 'Genderqueer', 'Buyer Representation', 10);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (8768, 'Hana', 'Joan', 'Ukraine', 'Female', 'JDE CNC', 11);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (4811, 'Tabbatha', 'Belliss', 'United States', 'Female', 'Ajax4JSF', 6);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (6603, 'Denver', 'Hughf', 'Sierra Leone', 'Male', 'Yardi Property Management', 21);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (2079, 'Maurie', 'Haycraft', 'Paraguay', 'Male', 'Otoplasty', 24);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (3608, 'Daffy', 'Kiefer', 'China', 'Female', 'Affiliate Marketing', 18);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (9859, 'Didi', 'Dafydd', 'Russia', 'Bigender', 'ILM', 16);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (7985, 'Jacinthe', 'Seale', 'China', 'Female', 'Sleep Medicine', 7);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (9780, 'Kellina', 'Meaders', 'Philippines', 'Female', 'Vulnerability Scanning', 23);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (3860, 'Harrietta', 'Pounder', 'Indonesia', 'Female', 'Pyramid', 8);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (6328, 'Doll', 'Colliford', 'Russia', 'Female', 'BBEdit', 18);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (7564, 'Basile', 'Cawsey', 'China', 'Non-binary', 'DNS', 6);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (6638, 'Mitchel', 'Tompsett', 'China', 'Male', 'CBEST', 8);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (9046, 'Jacenta', 'Bartholomieu', 'Brazil', 'Female', 'Evangelism', 7);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (8707, 'Burke', 'Alenichicov', 'South Korea', 'Male', 'Creative Writing', 24);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (8360, 'Korrie', 'Gianetti', 'Poland', 'Female', 'European Affairs', 16);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (5545, 'Missie', 'Hurtado', 'Indonesia', 'Female', 'Type Design', 4);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (7949, 'Shea', 'Scrimgeour', 'Sweden', 'Male', 'KMS', 1);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (8482, 'Ewan', 'Canland', 'Portugal', 'Male', 'NTSC', 21);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (3530, 'Jaquenette', 'Petrillo', 'Honduras', 'Female', 'WLI', 18);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (6529, 'Conway', 'Piggen', 'Niger', 'Male', 'Black Belt', 3);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (6868, 'Maxwell', 'Wassung', 'Indonesia', 'Male', 'TSCM', 19);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (6960, 'Keven', 'Lemmanbie', 'Poland', 'Male', 'Value Engineering', 24);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (1517, 'Derron', 'Lewsam', 'Netherlands', 'Male', 'Employee Relations', 23);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (8812, 'Sayre', 'Holtham', 'Japan', 'Female', 'LBO', 3);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (4100, 'Annmarie', 'Greste', 'Russia', 'Female', 'GMC PrintNet T', 14);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (2324, 'Robbyn', 'Gerdts', 'Russia', 'Female', 'DME', 24);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (1510, 'Davidde', 'Dunnan', 'Russia', 'Male', 'Curriculum Design', 9);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (6994, 'Byran', 'Desseine', 'Paraguay', 'Male', 'Nikon DSLR', 12);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (7228, 'Alan', 'Tomasek', 'China', 'Male', 'Vessel Operations', 15);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (5276, 'Samara', 'Vick', 'Belarus', 'Female', 'Single Family Homes', 20);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (1622, 'Lorry', 'Fosher', 'Indonesia', 'Male', 'JDBC', 19);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (1014, 'Marje', 'Lishman', 'Thailand', 'Polygender', 'IT Infrastructure Management', 9);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (1260, 'Karry', 'Fernie', 'Uganda', 'Female', 'NSA-IAM', 20);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (4821, 'Adair', 'Rampley', 'Serbia', 'Male', 'CDL Class B', 16);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (1726, 'Cello', 'Edler', 'Indonesia', 'Male', 'nCloth', 6);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (7467, 'Margery', 'Rowbottam', 'Chile', 'Female', 'RHEV', 24);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (2589, 'Magnum', 'Kell', 'Mali', 'Male', 'Press Releases', 21);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (1971, 'Horacio', 'Hann', 'France', 'Male', 'FW', 2);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (8152, 'Thomas', 'Blakey', 'United States', 'Male', 'Global Human Resources Management', 12);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (1518, 'Levey', 'Balas', 'France', 'Male', 'EPC', 9);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (6353, 'Merrill', 'Glennon', 'Portugal', 'Male', 'Chronic Illness', 6);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (8607, 'Cassandre', 'Howels', 'Indonesia', 'Female', 'Cross-functional Coordination', 14);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (1179, 'Bard', 'Westney', 'Mali', 'Male', 'Criminal Law', 6);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (4018, 'Bil', 'Grugerr', 'Sweden', 'Male', 'Film Production', 11);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (8355, 'Merci', 'Kilban', 'Laos', 'Female', 'User Experience Design', 25);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (2789, 'Greta', 'Stuchburie', 'Indonesia', 'Female', 'JSF', 2);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (7994, 'Man', 'Bolingbroke', 'Philippines', 'Male', 'PFI', 5);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (3578, 'Caprice', 'Seldner', 'South Africa', 'Female', 'JMX', 5);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (9215, 'Helene', 'Chastanet', 'Croatia', 'Female', 'Novels', 10);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (1488, 'Isidoro', 'Brimmacombe', 'China', 'Male', 'High Yield', 14);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (2074, 'Christye', 'Bartlomiejczyk', 'China', 'Female', 'DxDesigner', 19);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (9676, 'Ellswerth', 'Alesio', 'China', 'Male', 'Vsftpd', 3);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (6759, 'Rozamond', 'Turfin', 'Indonesia', 'Female', 'SFR', 19);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (7328, 'Cicely', 'Von Brook', 'Portugal', 'Female', 'Cvent', 1);
insert into CANDIDATE_DATA (id, first_name, last_name, country, gender, skill, years_experience) values (6422, 'Haven', 'Visick', 'China', 'Male', 'SNMP', 9);
